
## YAML Template.
---
server:
  port: 9006

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: ANGGOTA-SERVICE
            uri: lb://ANGGOTA-SERVICE
            predicates:
              - Path=/api/anggota/**  # <-- CORRECTED

          - id: BUKU-SERVICE
            uri: lb://BUKU-SERVICE
            predicates:
              - Path=/api/buku/**     # <-- CORRECTED

          - id: PEMINJAMAN-SERVICE
            uri: lb://PEMINJAMAN-SERVICE
            predicates:
              - Path=/api/peminjaman/** # <-- CORRECTED

          - id: PENGEMBALIAN-SERVICE
            uri: lb://PENGEMBALIAN-SERVICE
            predicates:
              - Path=/api/pengembalian/** # <-- CORRECTED

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost